### ISSUE TITLE
Laravel 5.7 Support

### ISSUE THREAD

**Issue by pankaj-sj** [spatie/laravel-personal-data-export#14]
**Hi**, 
This package doesn't support **Laravel 5.7**.
Is there any way I can use this in my 5.7 setup  as my production environment uses **5.7**.

**Comment by freekmurze** [comment]
We don't support Laravel 5.8 anymore. Feel free to fork our package and make the necessary modifications yourself.

**Comment by AlexisSerneels** [comment]
We don't support Laravel 5.8 anymore.
What?? You meant you don't support **5.7** right?

**Comment by freekmurze** [comment]
@AlexisSerneels yeah
