### ISSUE TITLE
Files added using addFile() with disk parameter are not included in final zip

### ISSUE THREAD

**Issue by AlexisSerneels** [spatie/laravel-personal-data-export#18]
This issue is debugged and fixed in my PR https://github.com/spatie/laravel-personal-data-export/pull/19

The tests were green because `selectPersonalData` in the User test Model was not using the optional disk parameter and then not testing against `copyFileFromDisk` method.
I've improved the test to cover this case scenario.

You can recreate the issue by removing `$this->files[] = $pathInTemporaryDirectory;` (line 88) from `PersonalDataSelection.php` from my PR and the test will fail.

**Comment by freekmurze** [comment]
We'll handle this in #19
