### ISSUE TITLE
Class PersonalDataExportController does not exist

### ISSUE THREAD

**Issue by AlexisSerneels** [spatie/laravel-personal-data-export#20]
The error is debugged and fixed in PR https://github.com/spatie/laravel-personal-data-export/pull/17

Currently, when trying to download the archive, it creates a `App\Http\Controllers\Spatie\PersonalDataExport\Http\Controllers\PersonalDataExportController does not exist` error.

Please see more information in the PR.

**Comment by freekmurze** [comment]
Thanks!
