### ISSUE TITLE
Dispatch won't work

### ISSUE THREAD

**Issue by Jelle0637** [spatie/laravel-personal-data-export#21]
`Argument 1 passed to Spatie\PersonalDataExport\Jobs\CreatePersonalDataExportJob::__construct() must be an instance of Spatie\PersonalDataExport\ExportsPersonalData, instance of App\User given, called in /app/Http/Controllers/ExportController.php on line 17`

I'm dispatching it as follow:
`dispatch(new CreatePersonalDataExportJob(auth()->user()));`

**Comment by atymic** [comment]
You need to implement the `ExportsPersonalData` interface on your `User` model as per
https://github.com/spatie/laravel-personal-data-export#selecting-personal-data

**Comment by hazem-taha** [comment]
I'm still getting this error although my Customer model is implementing the `ExportsPersonalData` interface and added the related two methods to the model.
