### ISSUE TITLE
Laravel ^6.0 support

### ISSUE THREAD

**Issue by affektde** [spatie/laravel-personal-data-export#30]
Wouldn't it have to be written?
Laravel 6.0.3 is now live.

```
        "illuminate/filesystem": "^5.8.3|^6.0",
        "illuminate/queue": "^5.8.3|^6.0",
        "illuminate/support": "^5.8.3|^6.0",
```

**Comment by freekmurze** [comment]
The latest version supports L6: https://github.com/spatie/laravel-personal-data-export/blob/1.2.0/composer.json#L24-L26
