### ISSUE TITLE
Error while updating laravel to 6.0.3

### ISSUE THREAD

**Issue by vishalinfyom** [spatie/laravel-personal-data-export#31]
Current Laravel version : `v6.0.0`
My current laravel-personal-data-export version is : `1.2.0`

while to upgrading laravel to 6.0.3 and getting this error.

![image](https://user-images.githubusercontent.com/33887755/64845990-1cff3000-d629-11e9-94f1-4cdff2607b87.png)

May be its cause by https://github.com/spatie/laravel-personal-data-export/blob/1.2.0/composer.json#L24

i think it should be `        "illuminate/filesystem": "^5.8.3|^6.0",`

Possible solution : https://github.com/spatie/laravel-personal-data-export/pull/32

**Comment by riasvdv** [comment]
Fixed!
