### ISSUE TITLE
Can i add my custom folder/directory ??  

### ISSUE THREAD

**Issue by vishalinfyom** [spatie/laravel-personal-data-export#34]
as this pacakge allow to add json file, can i add my custom folder and data into it.

e.g

MyZip.zip
 - users.json
 - Media
    - file.jpg

**Comment by freekmurze** [comment]
See: https://github.com/spatie/laravel-personal-data-export#selecting-personal-data

**Comment by vishalinfyom** [comment]
@freekmurze i already read that portion, my question is,

**IS THERE ANY SUPPORT TO ADD MY CUSTOM DIRECTORY INTO ZIP ???**

**Comment by vishalinfyom** [comment]
@riasvdv may be you can help on this ??

**Comment by freekmurze** [comment]
Just iterate through the files of your directory and use `addFile` to add it to the selection.

Please do not use all caps on this issue tracker, we consider that as shouting / rude.
