### ISSUE TITLE
Can I use this package on another model than a user ?

### ISSUE THREAD

**Issue by philippejadin** [spatie/laravel-personal-data-export#37]
Hope it's the right place to ask. Thank you for your package!

Can I use this to export data from a group model containing a lot of related models and attached files?

The group model is here fyi : https://github.com/philippejadin/agorakit/blob/master/app/Group.php

The idea would be to allow group admin to export a complete zip file of their groups.

Good idea or not to use this package?

**Comment by freekmurze** [comment]
You can implement `ExportsPersonalData` on any model you want.
