### ISSUE TITLE
Queue job should use default Job traits

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-personal-data-export#41]
By default a Laravel Job uses `Dispatchable, InteractsWithQueue, Queueable, SerializesModels`.
The queue job provided by the package should use all of them.
* `Dispatchable`: will allow to let the job dispatch itself
* `InteractsWithQueue`: is optional sugar on the cake
* `Queueable`: will allow to define the queue and connection of the job
* `SerializesModels`: should be required because the job accepts and handles an eloquent model

**Comment by freekmurze** [comment]
Feel free to PR improvements around this. It might also be nice to let the user, in the config file, specify the job class to be used

**Comment by Gummibeer** [comment]
Because the user has to self dispatch the job I don't see any need for a config value. There isn't any controller or something dispatching the job inside the package.
The only useful thing in config would be to define the queue and connection.
Will open a PR.
