### ISSUE TITLE
Not working when "authentication_required" is true

### ISSUE THREAD

**Issue by vmiguellima** [spatie/laravel-personal-data-export#48]
When is set **authentication_required** to true on the config, it always returns forbidden. Even when the user is logged in. I've dump **EnsureAuthorizedToDownload** Middleware, and it can't access current user instance.

I've tried so many ways and can't get it working with authorization, only works when disabled.

I'm using Laravel 8.

Thanks,
Miguel

**Comment by freekmurze** [comment]
The `it_can_download_the_personal_data_download` proves that the functionality is working as intended. Please submit a failing test for me to look at.

**Comment by rabol** [comment]
I just had the same issue and I my case this solved it:

// in your routes file - then if the user is not logged in, he will be prompted for user name and password
Route::middleware(['auth'])->group(function () {
    Route::personalDataExports('personal-data-exports');
});
