### ISSUE TITLE
Obsolete Mail documentation

### ISSUE THREAD

**Issue by QuentinGab** [spatie/laravel-personal-data-export#63]
Version : 2.0.2

The documentation suggest to customize Mail notification by extending `\Spatie\PersonalDataExport\Mail\PersonalDataExportCreatedMail `  but actually it is `Spatie\PersonalDataExport\Notifications\PersonalDataExportedNotification` that has to be extended.

**Comment by freekmurze** [comment]
Feel free to send a PR to update the docs 👍
